# Generated by Django 3.2.12 on 2023-04-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('date_created', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
